### ISSUE TITLE
site: migrate squarespace blog articles to tumblr

### ISSUE THREAD

**Issue by sohocoke** [bigbearlabs/webbuddy-support#52]

**Comment by sohocoke** [comment]
Hi Philipp,
- the migrated article list seems incomplete;
- the article dates reflect date of migration, not date of post.

Is it worth trying to fix these things, or shall we just leave the squarespace blog for 1.1? 

I think we should just cname the blog subdomain to squarespace and work on other stuff. What do you think?

**Comment by philippkueng** [comment]
well, the date might be the only issue we have. ...also i haven't migrated more posts, since i need your AWS credentials to upload your preview into the S3 bucket.

I'd migrate all the posts since that way you can save a lot of money, plus you get higher visibility.

**Comment by philippkueng** [comment]
everything's migrated. since binary files shouldn't be added to the git-repo ...because heroku doesn't like repos exceeding 100MB i dropped the 3 binary webbuddy preview files into my public dropbox folder. ...we can change that later in case you want to ...but i'm never deleting that anyway. 

Also i added a 301 redirect rule to the .htaccess file within bbl-site so as soon as bbl-site becomes bigbearlabs.com then the redirect is working and you can kill the squarespace account.
